name: amity_nt
description: "A new Flutter project."
 
 
publish_to: 'none'  

 
 
 
 
 
 
 
 
 
 
 
 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

 
 
 
 
 #............................Packages.............................#
 
dependencies:
  flutter:
    sdk: flutter


   
   
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  connectivity_plus: ^6.1.0
  hive: ^2.2.3
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  device_info_plus: ^11.1.0
  flutter_size: ^1.0.1
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

   
   
   
   
#....................Packages End..............................#
  flutter_lints: ^4.0.0

 
 

 
flutter:

   
   
   
  uses-material-design: true

#..........................Assets..........................#
  assets:
    - assets/images/app_logo/
    - assets/images/screen_image/
#.........................Fonts.............................#

   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
